GET http://localhost:8000/users/name/sample

###

GET http://localhost:8000/users

### 

GET http://localhost:8000/users/email/email2@wai.com

### 

GET http://localhost:8000/users/id/1

### 

POST http://localhost:8000/users HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "email": "email2@wai.com"
}
